name: CI - Run checks for lint, types and tests

on:
  push:
    branches: [ master ]
    tags-ignore: ['v.*']
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - run: npm pkg delete scripts.prepare

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check lint
        run: pnpm lint

      - name: Check type
        run: pnpm typecheck

      - name: Check test
        run: pnpm test
